---
apiVersion: v1
kind: Service
metadata:
  name: vm-postgres
spec:
  ports:
  - protocol: TCP
    name: http
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vm-postgres
subsets:
  - addresses:
      - ip: 35.233.36.172
    ports:
      - port: 5432
        name: http
